import re

db_path = r'c:\Users\psw71\.gemini\antigravity\scratch\tokyo-flooring\src\data\materials.db.js'

with open(db_path, 'r', encoding='utf-8') as f:
    content = f.read()

# I want to find all items (as dictionaries) and check their fields
# This is tricky because they are often generated by map()
# But I can check the source arrays: LIST_SHINHAN_IRIS_FILES, LIST_SHINHAN_PINEHEIM_FILES, LIST_SHINHAN_FIRE_RETARDANT_FILES

def find_array_content(array_name):
    match = re.search(fr'const {array_name} = \[\s*(.*?)\s*\];', content, re.DOTALL)
    if match:
        return match.group(1)
    return ""

iris_files = find_array_content("LIST_SHINHAN_IRIS_FILES")
pineheim_files = find_array_content("LIST_SHINHAN_PINEHEIM_FILES")
fire_files = find_array_content("LIST_SHINHAN_FIRE_RETARDANT_FILES")

print("--- IRIS FILES CHECK ---")
if "월가드" in iris_files or "WALLGUARD" in iris_files.upper() or '"W' in iris_files:
    print("Found potential Wallguard in IRIS (Hapji)")
    # Extract specific offending items
    offenders = [f for f in iris_files.split(',') if "월가드" in f or "WALLGUARD" in f.upper() or '"W' in f]
    print(offenders)

print("\n--- PINEHEIM FILES CHECK ---")
if "월가드" in pineheim_files or "WALLGUARD" in pineheim_files.upper() or '"W' in pineheim_files:
    print("Found potential Wallguard in PINEHEIM (Hapji)")
    offenders = [f for f in pineheim_files.split(',') if "월가드" in f or "WALLGUARD" in f.upper() or '"W' in f]
    print(offenders)

print("\n--- FIRE RETARDANT FILES CHECK ---")
if "월가드" in fire_files or "WALLGUARD" in fire_files.upper() or '"W' in fire_files:
    print("Found potential Wallguard in FIRE RETARDANT")
    offenders = [f for f in fire_files.split(',') if "월가드" in f or "WALLGUARD" in f.upper() or '"W' in f]
    print(offenders)

# Check individual exports for LIST_SHINHAN_... as well
# (Those that were exported as objects directly in generated code)
print("\n--- GENERATED OBJECTS CHECK ---")
# Find all occurrences of "collection": "월가드" and check their "materialType"
items = re.findall(r'\{[^{}]*?"collection":\s*"월가드"[^{}]*?\}', content, re.DOTALL)
count = 0
for item in items:
    if '"materialType": "실크"' not in item:
        print("Found Wallguard item NOT categorized as Silk:")
        print(item)
        count += 1
print(f"Total out-of-silk Wallguard items: {count}")

# Check for "materialType": "합지" or "방염" items that have "월가드" in their code or name
items_bad_cat = re.findall(r'\{[^{}]*?"materialType":\s*"(합지|방염)"[^{}]*?\}', content, re.DOTALL)
count_bad = 0
for item in items_bad_cat:
    if "월가드" in item or '"W' in item:
        print("Found item with wrong category having Wallguard name/code:")
        print(item)
        count_bad += 1
print(f"Total wrongly categorized Wallguard-like items: {count_bad}")
